spring:
  application:
    name: geosearch-server
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000

overpass:
  base-url: https://overpass-api.de/api/interpreter
  timeout: 30s
